MAES-7 ~ Fix platform config

diff --git a/.platform.app.yaml b/.platform.app.yaml
--- a/.platform.app.yaml
+++ b/.platform.app.yaml
@@ -123,9 +123,10 @@ hooks:
           fi
         done
 
-      cd /app
+        echo "***** Report site status *****"
+        cd /app
 
-      bash scripts/status/collect-all-sites.sh || echo "Status report failed (non-fatal), continuing deploy."
+        bash scripts/status/collect-all-sites.sh || echo "Status report failed (non-fatal), continuing deploy."
 
 web:
     locations:
@@ -159,10 +160,6 @@ web:
             rules:
                 ^/sites/default/files/(css|js):
                     expires: 2w
-  variables:
-    env:
-      GCS_BUCKET: 'unity_svr_2'
-      GCS_PREFIX: 'drupal-status'
 relationships:
     redis: 'redis:redis'
     mentalhealthchampionni: 'db:mentalhealthchampionni'
